# Generated by Django 5.2.6 on 2025-12-03 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='grade',
            field=models.ForeignKey(blank=True, help_text='Required only for Textbook subjects', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='library_app.grade'),
        ),
    ]
