# Generated by Django 5.2.6 on 2025-10-06 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='centre',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
    ]
