# Generated by Django 5.0.1 on 2025-12-01 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centre',
            options={'verbose_name': 'Library Centre', 'verbose_name_plural': 'Library Centres'},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Grades'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_other',
        ),
        migrations.AlterField(
            model_name='book',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='library_app.centre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='library_app.subject'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='historicalbook',
            name='isbn',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalbook',
            name='publisher',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['school'], name='library_app_school__74ba2e_idx'),
        ),
    ]
