# Generated by Django 5.2.6 on 2025-10-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='total_copies',
        ),
        migrations.RemoveField(
            model_name='historicalbook',
            name='total_copies',
        ),
        migrations.AlterField(
            model_name='book',
            name='available_copies',
            field=models.BooleanField(default=True, help_text='Indicates if the book is available (Yes/No).'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalbook',
            name='available_copies',
            field=models.BooleanField(default=True, help_text='Indicates if the book is available (Yes/No).'),
        ),
        migrations.AlterField(
            model_name='historicalbook',
            name='book_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalbook',
            name='isbn',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
