# Generated by Django 5.2.6 on 2025-12-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_alter_subject_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_other',
            field=models.BooleanField(default=True, help_text='Regular staff (accountant, guard, etc.)'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
