# Generated by Django 5.0.1 on 2025-09-26 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='CIN',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
