# Generated by Django 5.2.6 on 2025-10-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_remove_category_centre_remove_category_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='isbn',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
