# Generated by Django 5.0.1 on 2025-09-26 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_student_cin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='center',
        ),
        migrations.AddField(
            model_name='student',
            name='centre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='library_app.centre'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(max_length=500),
        ),
    ]
