# Generated by Django 5.0.1 on 2025-09-26 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_remove_student_center_student_centre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Books'},
        ),
        migrations.AlterModelOptions(
            name='historicalbook',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Book', 'verbose_name_plural': 'historical Books'},
        ),
        migrations.AddField(
            model_name='book',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_approved', to='library_app.customuser'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='reason_for_update',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='library_app.customuser'),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='reason_for_update',
            field=models.TextField(blank=True, null=True),
        ),
    ]
