# Generated by Django 5.0.1 on 2025-09-26 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_alter_book_options_alter_historicalbook_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historicalbook',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical book', 'verbose_name_plural': 'historical books'},
        ),
        migrations.RemoveField(
            model_name='book',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='book',
            name='reason_for_update',
        ),
        migrations.RemoveField(
            model_name='historicalbook',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='historicalbook',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='historicalbook',
            name='reason_for_update',
        ),
    ]
