# Generated by Django 5.2.6 on 2025-09-29 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_alter_book_options_alter_historicalbook_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
