# Generated by Django 5.0.1 on 2025-10-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_remove_book_available_copies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available_copies',
            field=models.BooleanField(default=True, help_text='Indicates if any copies are available (Yes/No).'),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='available_copies',
            field=models.BooleanField(default=True, help_text='Indicates if any copies are available (Yes/No).'),
        ),
    ]
