# Generated by Django 5.0.1 on 2025-09-30 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0007_alter_customuser_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='CIN',
            new_name='child_ID',
        ),
    ]
