# Generated by Django 5.0.1 on 2025-10-01 09:16

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('library_app', '0007_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_other',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_site_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now_add=True, help_text='The date and time when the book was borrowed.')),
                ('due_date', models.DateTimeField(help_text='The date by which the book must be returned.')),
                ('return_date', models.DateTimeField(blank=True, help_text='The date when the book was returned, if applicable.', null=True)),
                ('renewals', models.PositiveIntegerField(default=0, help_text='The number of times the borrow has been renewed.')),
                ('is_returned', models.BooleanField(default=False, help_text='Indicates whether the book has been returned.')),
                ('book', models.ForeignKey(help_text='The book being borrowed.', on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to='library_app.book')),
                ('centre', models.ForeignKey(help_text='The centre where the book was borrowed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrows', to='library_app.centre')),
                ('issued_by', models.ForeignKey(help_text='The user who issued the book.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_borrows', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user who borrowed the book.', on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalBorrow',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(blank=True, editable=False, help_text='The date and time when the book was borrowed.')),
                ('due_date', models.DateTimeField(help_text='The date by which the book must be returned.')),
                ('return_date', models.DateTimeField(blank=True, help_text='The date when the book was returned, if applicable.', null=True)),
                ('renewals', models.PositiveIntegerField(default=0, help_text='The number of times the borrow has been renewed.')),
                ('is_returned', models.BooleanField(default=False, help_text='Indicates whether the book has been returned.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('book', models.ForeignKey(blank=True, db_constraint=False, help_text='The book being borrowed.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='library_app.book')),
                ('centre', models.ForeignKey(blank=True, db_constraint=False, help_text='The centre where the book was borrowed.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='library_app.centre')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, db_constraint=False, help_text='The user who issued the book.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='The user who borrowed the book.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical borrow',
                'verbose_name_plural': 'historical borrows',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIssue',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('issue_date', models.DateTimeField(blank=True, editable=False, help_text='The date and time when the book was issued.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('book', models.ForeignKey(blank=True, db_constraint=False, help_text='The book being issued.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='library_app.book')),
                ('centre', models.ForeignKey(blank=True, db_constraint=False, help_text='The centre where the book is issued.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='library_app.centre')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, db_constraint=False, help_text='The user (librarian or admin) who issued the book.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='The user to whom the book is issued.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical issue',
                'verbose_name_plural': 'historical issues',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalNotification',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('message', models.TextField(help_text='The content of the notification.')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='The date and time when the notification was created.')),
                ('is_read', models.BooleanField(default=False, help_text='Indicates whether the notification has been read.')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='The ID of the related object.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('content_type', models.ForeignKey(blank=True, db_constraint=False, help_text='The type of object related to the notification.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, db_constraint=False, help_text='The user who responded to the notification, if applicable.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='The user who receives the notification.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical notification',
                'verbose_name_plural': 'historical notifications',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(auto_now_add=True, help_text='The date and time when the book was issued.')),
                ('book', models.ForeignKey(help_text='The book being issued.', on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='library_app.book')),
                ('centre', models.ForeignKey(help_text='The centre where the book is issued.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='library_app.centre')),
                ('issued_by', models.ForeignKey(help_text='The user (librarian or admin) who issued the book.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_issued', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user to whom the book is issued.', on_delete=django.db.models.deletion.CASCADE, related_name='issues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='The content of the notification.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time when the notification was created.')),
                ('is_read', models.BooleanField(default=False, help_text='Indicates whether the notification has been read.')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='The ID of the related object.', null=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='The type of object related to the notification.', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('responded_by', models.ForeignKey(blank=True, help_text='The user who responded to the notification, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='The user who receives the notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
