# Generated by Django 5.0.1 on 2025-10-01 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0008_customuser_is_other_customuser_is_site_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('school_code', models.CharField(max_length=30, unique=True)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.centre')),
            ],
        ),
    ]
