# Generated by Django 5.0.1 on 2025-10-02 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0009_alter_student_user_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='CIN',
            new_name='Child_ID',
        ),
    ]
