# Generated by Django 5.0.1 on 2025-10-02 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0010_rename_cin_student_child_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Child_ID',
            new_name='child_ID',
        ),
    ]
