# Generated by Django 5.0.1 on 2025-10-02 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0011_rename_child_id_student_child_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalissue',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The student to whom the book is issued.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='library_app.student'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='user',
            field=models.ForeignKey(help_text='The student to whom the book is issued.', on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='library_app.student'),
        ),
    ]
