# Generated by Django 5.0.1 on 2025-10-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0013_customuser_force_password_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
