# Generated by Django 5.0.1 on 2025-10-22 07:03

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0014_book_is_available_historicalbook_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCatalogue',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('shelf_number', models.CharField(help_text="The shelf location (e.g., 'A1', 'B2-3', 'Reference-1')", max_length=50)),
                ('added_date', models.DateTimeField(blank=True, editable=False, help_text='The date when the catalogue entry was created.')),
                ('last_updated', models.DateTimeField(blank=True, editable=False, help_text='The date when the catalogue entry was last updated.')),
                ('notes', models.TextField(blank=True, help_text="Additional notes about the book's location or condition.", null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this catalogue entry is currently active.')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('added_by', models.ForeignKey(blank=True, db_constraint=False, help_text='The user who added this catalogue entry.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(blank=True, db_constraint=False, help_text='The book being catalogued.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='library_app.book')),
                ('centre', models.ForeignKey(blank=True, db_constraint=False, help_text='The centre where the book is shelved.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='library_app.centre')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical catalogue',
                'verbose_name_plural': 'historical Catalogues',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_number', models.CharField(help_text="The shelf location (e.g., 'A1', 'B2-3', 'Reference-1')", max_length=50)),
                ('added_date', models.DateTimeField(auto_now_add=True, help_text='The date when the catalogue entry was created.')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='The date when the catalogue entry was last updated.')),
                ('notes', models.TextField(blank=True, help_text="Additional notes about the book's location or condition.", null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this catalogue entry is currently active.')),
                ('added_by', models.ForeignKey(help_text='The user who added this catalogue entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogues_added', to=settings.AUTH_USER_MODEL)),
                ('book', models.ForeignKey(help_text='The book being catalogued.', on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_entries', to='library_app.book')),
                ('centre', models.ForeignKey(help_text='The centre where the book is shelved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogues', to='library_app.centre')),
            ],
            options={
                'verbose_name_plural': 'Catalogues',
                'ordering': ['shelf_number'],
                'unique_together': {('book', 'centre')},
            },
        ),
    ]
