# Generated by Django 5.0.1 on 2025-10-22 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0015_historicalcatalogue_catalogue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='available_copies',
        ),
        migrations.RemoveField(
            model_name='historicalbook',
            name='available_copies',
        ),
    ]
